databaseChangeLog:
  - changeSet:
      id: 3.15.0
      author: GraviteeSource Team
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}flow_steps
            columns:
              - column:
                  name: condition
                  type: nvarchar(256)
                  constraints:
                    nullable: true
